services:
  - type: web
    name: qr-code-generator
    env: docker
    plan: free
    branch: main
    repo: https://github.com/reuel-k/Devops-QRCodeGenerator
    dockerfilePath: Dockerfile
    envVars:
      - key: SERVER_PORT
        value: 1111
